# 1. Basic Python

In [2]:
lst = [n for n in range(0,10)]
#print(lst)
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
def add_nums(x,y):
    return x+y

add_nums(1,2)

3

In [4]:
my_list = [1,2,3,4,5]
my_list.append(6) 
my_list

[1, 2, 3, 4, 5, 6]

In [5]:
my_list[0]

1

In [6]:
my_list + ['a','b','c']

[1, 2, 3, 4, 5, 6, 'a', 'b', 'c']

In [7]:
1 in my_list

True

In [8]:
my_list[0:3]

[1, 2, 3]

In [9]:
fullName = 'Andrea Alvarez Rodriguez'
firstName = fullName.split(" ")[0]
secondLastName = fullName.split(" ")[-1]
print(firstName)
print(secondLastName)

Andrea
Rodriguez


In [10]:
x = {"David Arango": "david@gmail.com", "Andrea Alvarez": "andrea@gmail.com"}
x

{'Andrea Alvarez': 'andrea@gmail.com', 'David Arango': 'david@gmail.com'}

In [11]:
x["David Arango"]

'david@gmail.com'

In [12]:
x["Catalina Arango"] = "cata@gmail.com"
x

{'Andrea Alvarez': 'andrea@gmail.com',
 'Catalina Arango': 'cata@gmail.com',
 'David Arango': 'david@gmail.com'}

In [13]:
store1 = [10.0, 10.5, 11.3]
store2 = [10.2, 10.1, 11.5]
cheapest = map(min, store1, store2)
cheapest

In [14]:
list(cheapest)

[10.0, 10.1, 11.3]

In [15]:
"the story of {0} and {1} and {c}".format("a","b", c="c")

'the story of a and b and c'

# 2. Numpy Library

In [16]:
import numpy as np

In [17]:
#creating a numpy array:
my_list = [1,2,3] #python list
array1 = np.array(my_list) #pass python list to numpy array
array1

array([1, 2, 3])

In [18]:
# or more succint:
array1 = np.array([11,12,13])
array1

array([11, 12, 13])

In [19]:
#multidimensional arrays:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#checking dimensions of an array:
array1.shape

(3, 3)

In [21]:
#creating an evenly-spaced array:
array1 = np.arange(0,30,2) #(start,end,step-size)
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [22]:
#reshaping an array:
array1 = array1.reshape(3,5)
array1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [23]:
#create array with fixed number of elements, and defined range
array1 = np.linspace(0,4,9) # (start,end,number of elements)
array1

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [24]:
# resizing an array (does not create new array, modifies original)
array1.resize(3,3)
array1

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [25]:
# ones array
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# zeros array
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# identity array
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# diagonal array from vector:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [29]:
# create array2 by repeating array1:
np.array([[1,2,3]*3,[4,5,6]*3]*3)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [30]:
# create array by repeating values:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [31]:
# array of ones, integers:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
#stacking vertically:
np.vstack([p,p*2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [33]:
#stacking horizontally:
np.hstack([p,p*3])

array([[1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3]])

## 2.1 Array Operations

In [34]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [35]:
x+y

array([5, 7, 9])

In [36]:
x*y

array([ 4, 10, 18])

In [37]:
x**2

array([1, 4, 9], dtype=int32)

In [38]:
x.dot(y)

32

In [39]:
z = np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [40]:
# Transpose of an array:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [41]:
z.T.shape

(3, 2)

In [42]:
z.dtype

dtype('int32')

In [43]:
# cast array to a different type:
z.astype('f')

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

## 2.2 Useful Functions

In [44]:
x.min()
x.max()
x.sum()

6

In [45]:
x.mean()
x.std()

0.816496580927726

In [46]:
# index of max and min values:
x.argmin()
x.argmax()

2

## 2.3 Indexing and Slicing

In [47]:
v = np.arange(13)**2
v

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [48]:
v[0],v[4],v[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [49]:
# slice from the end of the array:
v[-3:]


array([100, 121, 144], dtype=int32)

In [50]:
# downsampling an array:
v[::2]

array([  0,   4,  16,  36,  64, 100, 144], dtype=int32)

In [51]:
# extracting rows
z[0,:]

array([4, 5, 6])

In [52]:
# extracting cols
z[:,0:2]

array([[ 4,  5],
       [16, 25]])

In [53]:
# extract all cols except the last
z[:,:-1]

array([[ 4,  5],
       [16, 25]])

In [54]:
# extract elements that satisfy a condition:
z[z>5]


array([ 6, 16, 25, 36])

In [55]:
# change element values that satisfy a condition:
z[z>6]=10
z

array([[ 4,  5,  6],
       [10, 10, 10]])

## 2.4 Making Copies of Arrays

In [56]:
r = np.arange(24)
r.resize(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
s = r[:3,:3]
s

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [58]:
s[s>0]=0
s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
# s IS NOT A COPY OF r[:3,:3] ! they are the same registers
r

array([[ 0,  0,  0,  3],
       [ 0,  0,  0,  7],
       [ 0,  0,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
# to make a copy:
r_copy = r.copy()
r_copy[:] = 10
print(r)
print()
print(r_copy)


[[ 0  0  0  3]
 [ 0  0  0  7]
 [ 0  0  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [61]:
r_copy[0,:2]

array([10, 10])

## 2.5 Iterating Over Arrays

In [62]:
test = np.random.randint(0,10,(5,3))
test

array([[1, 9, 2],
       [5, 4, 5],
       [4, 3, 1],
       [3, 3, 1],
       [9, 1, 9]])

In [63]:
for row in test:
    print(row)

[1 9 2]
[5 4 5]
[4 3 1]
[3 3 1]
[9 1 9]


In [64]:
for i in range(len(test)):
    print(test[i])

[1 9 2]
[5 4 5]
[4 3 1]
[3 3 1]
[9 1 9]


In [65]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [1 9 2]
row 1 is [5 4 5]
row 2 is [4 3 1]
row 3 is [3 3 1]
row 4 is [9 1 9]


In [66]:
test2 = test**2
test2

array([[ 1, 81,  4],
       [25, 16, 25],
       [16,  9,  1],
       [ 9,  9,  1],
       [81,  1, 81]], dtype=int32)

In [67]:
for i,j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[1 9 2] + [ 1 81  4] = [ 2 90  6]
[5 4 5] + [25 16 25] = [30 20 30]
[4 3 1] + [16  9  1] = [20 12  2]
[3 3 1] + [9 9 1] = [12 12  2]
[9 1 9] + [81  1 81] = [90  2 90]


# 3. PANDAS Toolkit

In [68]:
import pandas as pd

## 3.1 The Series Data Structure

In [69]:
#pd.Series? # series documentation

In [70]:
# create series from a python list (look at the data types)
animals = ['dog', 'cat', 'bird']
pd.Series(animals)

0     dog
1     cat
2    bird
dtype: object

In [71]:
# create series from a python list (look at the data types)
numbers = [1,2,3,4,5]
pd.Series(numbers)

0    1
1    2
2    3
3    4
4    5
dtype: int64

## 3.2 Querying a Series

In [72]:
import numpy as np
import pandas as pd

#example series:
s = pd.Series([55,39,19,102,91])
s

0     55
1     39
2     19
3    102
4     91
dtype: int64

In [73]:
#query with .iloc propery, query with [], query with .loc property:

temp = s.iloc[0]
print('with iloc: ',  temp)
temp = s[0]
print('with []: ', temp)
temp = s.loc[0]
print('with loc: ',  temp)
# if we had index labels, .loc property would be diff from .iloc

with iloc:  55
with []:  55
with loc:  55


In [74]:
%%timeit -n 1000
total = 0
for item in s:
    total += item
#print(total)

17.7 µs ± 2.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [75]:
%%timeit -n 1000
total = np.sum(s)
#print(total)
#hmmmm.. the results do not make sense. Check later!

110 µs ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [76]:
#Broadcasting example: (apply an operation to a series and change its values directly)
s += 2
s.head()

0     57
1     41
2     21
3    104
4     93
dtype: int64

In [77]:
#not done by broadcasting...
for label, value in s.iteritems():
    s.loc[label] = value+2
    
s.head()    

0     59
1     43
2     23
3    106
4     95
dtype: int64

In [78]:
s = pd.Series(np.random.randint(0,10,5))
s

0    9
1    3
2    6
3    3
4    7
dtype: int32

In [79]:
s[5] = 4
s.loc[6] = 'string1'
s

0          9
1          3
2          6
3          3
4          7
5          4
6    string1
dtype: object

In [80]:
original_sports = pd.Series({'Soccer':'Brasil', 'Golf': 'Scotland', 'Tennis': 'Spain'})
original_sports

Golf      Scotland
Soccer      Brasil
Tennis       Spain
dtype: object

In [81]:
cricket_countries = pd.Series(['Australia','Barbados','Pakistan','India'], index = ['Cricket','Cricket','Cricket','Cricket'])
cricket_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket        India
dtype: object

In [82]:
all_countries = original_sports.append(cricket_countries)
all_countries

Golf        Scotland
Soccer        Brasil
Tennis         Spain
Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket        India
dtype: object

In [83]:
# the original series is not changed by the append operation!
cricket_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket        India
dtype: object

## 3.3 The DataFrame Data Structure

In [84]:
# ex: creating a DataFrame from multiple Series:
purchase1 = pd.Series({'Name': 'Dave', 'Item': 'Dog Food', 'Cost': 12.50})
purchase2 = pd.Series({'Name': 'Cata', 'Item': 'Cat Litter', 'Cost': 5.50})
purchase3 = pd.Series({'Name': 'Andre', 'Item': 'Bird Seed', 'Cost': 2.50})

df = pd.DataFrame([purchase1,purchase2,purchase3], index = ['store1','store1','store2'])
#df = pd.DataFrame([purchase1,purchase2,purchase3]) #if index not specified, it starts at 0
df

Cost        Item   Name
store1  12.5    Dog Food   Dave
store1   5.5  Cat Litter   Cata
store2   2.5   Bird Seed  Andre

In [85]:
# query wity unique index
df.loc['store2']

Cost          2.5
Item    Bird Seed
Name        Andre
Name: store2, dtype: object

In [86]:
# query with non-unique index
df.loc['store1']

Cost        Item  Name
store1  12.5    Dog Food  Dave
store1   5.5  Cat Litter  Cata

In [87]:
# if we need just one column returned from the query:
df.loc['store1']['Cost']
# this 'chaining' returns a copy, not a view on the dataframe. Try to avoid chaining

store1    12.5
store1     5.5
Name: Cost, dtype: float64

In [88]:
# This approach is more appropriate, even more if you´re modifying data on the df:
df.loc[:,['Item', 'Cost']]

Item  Cost
store1    Dog Food  12.5
store1  Cat Litter   5.5
store2   Bird Seed   2.5

In [89]:
# Dropping data (row): does not delete data from original DFrame
df.drop('store1')
df

Cost        Item   Name
store1  12.5    Dog Food   Dave
store1   5.5  Cat Litter   Cata
store2   2.5   Bird Seed  Andre

In [90]:
# Dropping data (row) permanently on a dataframe copy:
df_copy = df.drop('store1') 
df_copy

Cost       Item   Name
store2   2.5  Bird Seed  Andre

In [91]:
# You can also use the del keyword, using the indexing operator directly:
# This takes inmediate effect on the ORIGINAL DFrame
df_copy = df
del df_copy["Item"]
df

Cost   Name
store1  12.5   Dave
store1   5.5   Cata
store2   2.5  Andre

In [92]:
# adding a new column to the DataFrame:
df['Location']=None
df

Cost   Name Location
store1  12.5   Dave     None
store1   5.5   Cata     None
store2   2.5  Andre     None

In [93]:
# applying changes to a column on the DataFrame (Broadcasting)
# ex: 20% discount on all products:

df['Cost'] *= 0.8
df

Cost   Name Location
store1  10.0   Dave     None
store1   4.4   Cata     None
store2   2.0  Andre     None

In [94]:
df.columns

Index(['Cost', 'Name', 'Location'], dtype='object')

In [95]:
# renaming columns in a DataFrame:
df.rename(index=str, columns={"Cost": "Cost!", "Name": "Name!"})

Cost!  Name! Location
store1   10.0   Dave     None
store1    4.4   Cata     None
store2    2.0  Andre     None